apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  namespace: axion-app
spec:
  selector:
    matchLabels:
      app: ui-deployment
  template:
    metadata:
      labels:
        app: ui-deployment
    spec:
      containers:
      - name: ui-deployment
        image: bhawanidocker/axion-ui:1.0.1
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
