apiVersion: v1
kind: Secret
metadata:
  name: secret-db
  namespace: axion-app
type: Opaque
stringData:
# pgAdmin Secret
  PGADMIN_DEFAULT_EMAIL: admin@pg.com
  PGADMIN_DEFAULT_PASSWORD: admin@123
  
# PostgreSQL Secret
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin123
  POSTGRES_DB: axiondb